[package]
name = "snu-graphics-raytracer"
version = "0.1.0"
authors = ["SeongChan Lee <foriequal@gmail.com>"]

[dependencies]
cgmath = "0.16.1"
rayon = "1.0.1"
palette = "0.4"
png = "0.12.0"
num-traits = "0.2"
itertools = "0.7.8"
stopwatch = "0.0.7"
rand = "0.5.0"
tobj = "0.1.6"